# Generated by Django 5.2.17 on 2026-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_selector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
